title: DBLOG
author: Doveccl
copy: "&copy; 2015-2018"

path: ""
home: "/"
url: "https://ecl.me"

links:
  About: /about.html
  Friends: /friends.html
  Feeds: /feed.xml

disqus:
  url: "//test.disqus.com"

excerpt_separator: "<!--more-->"

paginate: 5
paginate_path: "page:num"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
- jekyll-feed
- jekyll-paginate

exclude:
- README.md
